### ISSUE TITLE
Update dong bang, gw install di arch linux, udah konek tapi gak bisa ping ke dns google

### ISSUE THREAD

**Issue by alfatihart** [ryanfauzi1/xderm-mini#2]

**Comment by ryanfauzi1** [comment]
kalo ping emang ga bs pak.. kecuali httping, atau fping yg koneksinya tcp,
umpama konek tpi ga bs browsing mungkin penyebabnya ga bs resolv dns.. bisa
dicoba ketik /etc/init.d/dnsmasq restart

Pada tanggal Sab, 27 Feb 2021 12.42, Al-Fatih Art <notifications@github.com>
menulis:

**Comment by alfatihart** [comment]
ok bang
